development:
  adapter: postgresql
  encoding: unicode
  database: terence_email_test
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: terence_email_test
  pool: 5
  username: gschool
  password:
